<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="smart_car">

  <!-- Robot parameters -->
  <xacro:property name="wheel_diameter" value="0.064"/>
  <xacro:property name="wheel_radius" value="${wheel_diameter/2.0}"/>
  <xacro:property name="wheel_width" value="0.025"/>
  <xacro:property name="wheelbase_length" value="0.257"/>
  <xacro:property name="wheelbase_width" value="0.17"/>

  <!-- Base footprint -->
  <link name="base_footprint"/>

  <!-- Chassis -->
  <link name="chassis_link">
    <inertial>
      <origin xyz="0 0 0.05" rpy="0 0 0"/>
      <mass value="2.0"/>
      <inertia ixx="0.02" iyy="0.02" izz="0.04" ixy="0.0" ixz="0.0" iyz="0.0"/>
    </inertial>
    <visual>
      <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} 0.05"/>
      </geometry>
      <material name="blue">
        <color rgba="0 0 1 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${wheelbase_length} ${wheelbase_width} 0.05"/>
      </geometry>
    </collision>
  </link>

  <!-- Connect base_footprint to chassis -->
  <joint name="base_to_chassis" type="fixed">
    <parent link="base_footprint"/>
    <child link="chassis_link"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
  </joint>

  <!-- MACRO for wheels -->
  <xacro:macro name="wheel" params="name x y">
    <link name="${name}_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" iyy="0.001" izz="0.002" ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
    </link>

    <joint name="${name}_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="${name}_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 1.5708 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- MACRO for steering -->
  <xacro:macro name="steering_wheel" params="side x y">
    <!-- Steering link -->
    <link name="front_${side}_steer_link">
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.05"/>
        <inertia ixx="0.0005" iyy="0.0005" izz="0.001" ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
    </link>

    <!-- Steering joint -->
    <joint name="front_${side}_wheel_steer_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="front_${side}_steer_link"/>
      <origin xyz="${x} ${y} 0" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785" upper="0.785" effort="1" velocity="1"/>
    </joint>

    <!-- Wheel link -->
    <link name="front_${side}_wheel_link">
      <visual>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
        <material name="black"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
        </geometry>
      </collision>
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.1"/>
        <inertia ixx="0.001" iyy="0.001" izz="0.002" ixy="0.0" ixz="0.0" iyz="0.0"/>
      </inertial>
    </link>

    <!-- Wheel joint -->
    <joint name="front_${side}_wheel_joint" type="continuous">
      <parent link="front_${side}_steer_link"/>
      <child link="front_${side}_wheel_link"/>
      <origin xyz="0 0 0" rpy="0 1.5708 0"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>

  <!-- BACK WHEELS -->
  <xacro:wheel name="back_left_wheel"  x="-${wheelbase_length/2}" y="${wheelbase_width/2}"/>
  <xacro:wheel name="back_right_wheel" x="-${wheelbase_length/2}" y="-${wheelbase_width/2}"/>

  <!-- FRONT WHEELS with steering -->
  <xacro:steering_wheel side="left"  x="${wheelbase_length/2}" y="${wheelbase_width/2}"/>
  <xacro:steering_wheel side="right" x="${wheelbase_length/2}" y="-${wheelbase_width/2}"/>

</robot>

